//! Generates `circuits/kat/proof_compression_kat.json`: a Rust->TS
//! compression known-answer-test. Compresses the real
//! `circuits/target/transfer_multisig.proof` fixture (the uncompressed
//! 388-byte Groth16 layout) host-side with `solana_bn254`'s REAL BN254
//! compression -- the exact algorithm `packages/prover`'s TS `compressProof`
//! must reproduce byte-for-byte for the on-chain wire format (workstream G,
//! see `programs/kakure_pool/src/instruction.rs`'s module docs) to work.
//!
//! Run as a normal test (`cargo test --test proof_compression_kat`); it is
//! a fixture-GENERATING test, not an assertion, so it always passes once
//! the fixture exists and simply (re)writes the JSON -- this way it stays
//! in CI's normal test run and never goes silently stale.

mod common;

#[test]
fn generate_proof_compression_kat() {
    let circuits_target = std::path::PathBuf::from(
        std::env::var("KAKURE_CIRCUITS_TARGET").unwrap_or_else(|_| {
            format!("{}/kakure/circuits/target", std::env::var("HOME").unwrap_or_else(|_| "/root".to_string()))
        }),
    );
    let proof_path = circuits_target.join("transfer_multisig.proof");
    if !proof_path.exists() {
        eprintln!(
            "SKIP generate_proof_compression_kat: {proof_path:?} not found \
             (run workstream A's `just build-circuits` first)"
        );
        return;
    }

    let uncompressed = std::fs::read(&proof_path).unwrap();
    assert_eq!(uncompressed.len(), 388, "unexpected .proof length (expected uncompressed 388-byte layout)");

    let a = &uncompressed[0..64];
    let b = &uncompressed[64..192];
    let c = &uncompressed[192..256];
    let commitment_count = u32::from_be_bytes(uncompressed[256..260].try_into().unwrap());
    assert_eq!(commitment_count, 1, "expected exactly one Pedersen commitment");
    let commitment = &uncompressed[260..324];
    let pok = &uncompressed[324..388];

    use solana_bn254::compression::prelude::{alt_bn128_g1_compress, alt_bn128_g2_compress};
    let a_compressed = alt_bn128_g1_compress(a).expect("compress A");
    let b_compressed = alt_bn128_g2_compress(b).expect("compress B");
    let c_compressed = alt_bn128_g1_compress(c).expect("compress C");
    let commitment_compressed = alt_bn128_g1_compress(commitment).expect("compress commitment");
    let pok_compressed = alt_bn128_g1_compress(pok).expect("compress pok");

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    let json = format!(
        "{{\n  \"_comment\": \"Rust\\u2192TS Groth16 proof-compression KAT (workstream G). Generated by tests-litesvm/tests/proof_compression_kat.rs from circuits/target/transfer_multisig.proof (the uncompressed A(64)||B(128)||C(64)||commitment_count(4)||commitment(64)||pok(64) layout), compressed with solana_bn254's REAL (not mocked) BN254 compression. packages/prover's TS compressProof() must reproduce these hex strings byte-for-byte from the same uncompressed proof.\",\n  \"source\": \"circuits/target/transfer_multisig.proof\",\n  \"uncompressed\": {{\n    \"A\": \"{}\",\n    \"B\": \"{}\",\n    \"C\": \"{}\",\n    \"commitment\": \"{}\",\n    \"pok\": \"{}\"\n  }},\n  \"compressed\": {{\n    \"A\": \"{}\",\n    \"B\": \"{}\",\n    \"C\": \"{}\",\n    \"commitment\": \"{}\",\n    \"pok\": \"{}\"\n  }}\n}}\n",
        hex(a),
        hex(b),
        hex(c),
        hex(commitment),
        hex(pok),
        hex(&a_compressed),
        hex(&b_compressed),
        hex(&c_compressed),
        hex(&commitment_compressed),
        hex(&pok_compressed),
    );

    let out_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../circuits/kat/proof_compression_kat.json");
    std::fs::write(&out_path, &json).unwrap_or_else(|e| panic!("write {out_path:?}: {e}"));
    eprintln!("wrote {out_path:?}");

    // Round-trip sanity: decompressing what we just compressed must recover
    // the original uncompressed points -- the same guarantee the on-chain
    // `verify::decompress_proof` relies on.
    use solana_bn254::compression::prelude::{alt_bn128_g1_decompress, alt_bn128_g2_decompress};
    assert_eq!(alt_bn128_g1_decompress(&a_compressed).unwrap(), a);
    assert_eq!(alt_bn128_g2_decompress(&b_compressed).unwrap(), b);
    assert_eq!(alt_bn128_g1_decompress(&c_compressed).unwrap(), c);
    assert_eq!(alt_bn128_g1_decompress(&commitment_compressed).unwrap(), commitment);
    assert_eq!(alt_bn128_g1_decompress(&pok_compressed).unwrap(), pok);
}
