import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { compressG1, compressG2, compressProof, COMPRESSED_PROOF_LEN } from "../compress.js";

// KAT generated by tests-litesvm/tests/proof_compression_kat.rs (workstream G), by compressing
// circuits/target/transfer_multisig.proof host-side with solana_bn254's REAL (not mocked) BN254
// compression -- the exact byte-for-byte target this TS port must reproduce.
const KAT_PATH = fileURLToPath(new URL("../../../../circuits/kat/proof_compression_kat.json", import.meta.url));

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function loadKat() {
  const json = JSON.parse(readFileSync(KAT_PATH, "utf8")) as {
    uncompressed: Record<"A" | "B" | "C" | "commitment" | "pok", string>;
    compressed: Record<"A" | "B" | "C" | "commitment" | "pok", string>;
  };
  return json;
}

describe("compressProof (Rust->TS KAT)", () => {
  it("matches the Rust-generated KAT byte-for-byte for each proof element", () => {
    const kat = loadKat();
    expect(compressG1(hexToBytes(kat.uncompressed.A))).toEqual(hexToBytes(kat.compressed.A));
    expect(compressG2(hexToBytes(kat.uncompressed.B))).toEqual(hexToBytes(kat.compressed.B));
    expect(compressG1(hexToBytes(kat.uncompressed.C))).toEqual(hexToBytes(kat.compressed.C));
    expect(compressG1(hexToBytes(kat.uncompressed.commitment))).toEqual(hexToBytes(kat.compressed.commitment));
    expect(compressG1(hexToBytes(kat.uncompressed.pok))).toEqual(hexToBytes(kat.compressed.pok));
  });

  // slice-2 F-10: this used to read `~/kakure/circuits/target/transfer_multisig.proof` off disk --
  // but EVERY `prove()` run (real or via `just verify-kat`) overwrites that path with a FRESH
  // Groth16 proof (randomized: different A/B/C bytes each time, still valid for the same public
  // inputs), so it drifted out of sync with this committed KAT any time something else on the
  // machine had proved since the KAT was last regenerated -- "3 pass, 1 fail" on a perfectly
  // correct TS implementation. The full 388-byte uncompressed layout
  // (A(64)‖B(128)‖C(64)‖commitment_count:u32be=1‖commitment(64)‖pok(64), see `decode.ts`'s
  // `DecodedProof`) is fully reconstructable from the KAT JSON's own per-element hex -- already
  // proven correct byte-for-byte by the test above -- so build it in-memory instead of touching the
  // filesystem at all. This is green regardless of what any concurrent `prove()` run does to
  // `circuits/target`.
  it("compressProof on the KAT's own elements, reassembled, matches its full 192-byte concatenation", () => {
    const kat = loadKat();
    const commitmentCountBE = new Uint8Array(4);
    new DataView(commitmentCountBE.buffer).setUint32(0, 1, false);
    const proof = new Uint8Array([
      ...hexToBytes(kat.uncompressed.A),
      ...hexToBytes(kat.uncompressed.B),
      ...hexToBytes(kat.uncompressed.C),
      ...commitmentCountBE,
      ...hexToBytes(kat.uncompressed.commitment),
      ...hexToBytes(kat.uncompressed.pok),
    ]);
    expect(proof.length).toBe(388);

    const compressed = compressProof({ proof, publicInputs: [] });
    expect(compressed.length).toBe(COMPRESSED_PROOF_LEN);
    const expected = new Uint8Array([
      ...hexToBytes(kat.compressed.A),
      ...hexToBytes(kat.compressed.B),
      ...hexToBytes(kat.compressed.C),
      ...hexToBytes(kat.compressed.commitment),
      ...hexToBytes(kat.compressed.pok),
    ]);
    expect(compressed).toEqual(expected);
  });

  it("compresses the all-zero (point-at-infinity) encoding to all-zero", () => {
    expect(compressG1(new Uint8Array(64))).toEqual(new Uint8Array(32));
    expect(compressG2(new Uint8Array(128))).toEqual(new Uint8Array(64));
  });

  it("regression: a real e2e deposit proof's B point whose second serialized half ties its own negation (see circuits/kat/proof_compression_kat_g2_regression.json)", () => {
    // This KAT was NOT round-trip-safe under an earlier version of fq2SignFlagBit that compared
    // the two Fq2 coordinate halves in the wrong priority order -- the bug was invisible against
    // proof_compression_kat.json's single B point because that one's second half happened to tie
    // its own negation, making the (wrong) primary comparison moot there. This one's first half
    // does NOT tie, so it actually exercises which half decides the sign bit.
    const regressionPath = fileURLToPath(
      new URL("../../../../circuits/kat/proof_compression_kat_g2_regression.json", import.meta.url),
    );
    const kat = JSON.parse(readFileSync(regressionPath, "utf8")) as {
      uncompressed: { B: string };
      compressed: { B: string };
    };
    expect(compressG2(hexToBytes(kat.uncompressed.B))).toEqual(hexToBytes(kat.compressed.B));
  });
});
