// Master plan I-5 / spec §3.1 reconciliation: workstream A's shared KAT
// (`circuits/kat/lean_imt_poseidon_v1.json`, generated by circomlibjs and cross-checked against a Noir
// computation of `poseidon::bn254::hash_3`) landed on `main` after this package's own `PoseidonV1.test.ts`
// and `LeanImtParity.test.ts` were written against an independent naive-rebuild check (no external oracle
// was available yet at that point). This file is the actual cross-check flagged there: it loads A's KAT and
// asserts the SDK's `LeanIMT` (frontier insert + `getMerklePath`) reproduces every root and sibling array
// bit-for-bit. If this ever fails, the KAT is authoritative -- fix `crypto/PoseidonV1.ts`/`merkle/LeanIMT.ts`,
// never the fixture.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Fr } from "@aztec/foundation/fields";
import { LeanIMT } from "../merkle/LeanIMT.js";

const KAT_PATH = fileURLToPath(
  new URL("../../../../circuits/kat/lean_imt_poseidon_v1.json", import.meta.url),
);

interface KatEntry {
  readonly case: string;
  readonly leaf_index: number | null;
  readonly leaf: string | null;
  readonly next_leaf_index: number;
  readonly root: string;
  readonly siblings: readonly string[];
}
interface Kat {
  readonly depth: number;
  readonly entries: readonly KatEntry[];
}

function loadKat(): Kat {
  try {
    return JSON.parse(readFileSync(KAT_PATH, "utf8")) as Kat;
  } catch (err) {
    const why = err instanceof Error ? err.message : String(err);
    throw new Error(
      `circuits/kat/lean_imt_poseidon_v1.json missing or unreadable at ${KAT_PATH} (${why}). ` +
        "Workstream A publishes this fixture; run `git merge main` if it is missing here.",
    );
  }
}

function hexToFr(hex: string): Fr {
  return new Fr(BigInt(hex));
}

describe("LeanIMT vs workstream A's shared KAT (circuits/kat/lean_imt_poseidon_v1.json)", () => {
  const kat = loadKat();

  it("has the expected shape (depth 32, genesis case + leaves 1..8)", () => {
    expect(kat.depth).toBe(32);
    expect(kat.entries.length).toBe(9);
    expect(kat.entries[0]!.case).toBe("genesis");
  });

  it("reproduces every root and 32-sibling path bit-for-bit", async () => {
    const tree = new LeanIMT(kat.depth);

    for (const entry of kat.entries) {
      if (entry.case === "genesis") {
        // Pre-insert state: nothing has been inserted yet, so there is no valid leaf index to fold a
        // path from -- only the (zero) root is checked.
        expect(tree.nextLeafIndex).toBe(entry.next_leaf_index);
        expect(tree.getRoot().toString()).toBe(entry.root);
        continue;
      }

      await tree.insert(hexToFr(entry.leaf!));

      expect(tree.nextLeafIndex).toBe(entry.next_leaf_index);
      expect(tree.getRoot().toString()).toBe(entry.root);

      const siblings = tree.getMerklePath(entry.leaf_index!);
      expect(siblings.map((s) => s.toString())).toEqual(entry.siblings);
    }
  });
});
