// Regenerates circuits/manifest.json from the built .vk files under circuits/target/.
//
// circuit_id and public_input_count are the frozen interface values from the kakure master
// plan (I-1); vk_sha256 is computed from the actual built verifying key so any drift between
// a rebuilt circuit and the committed manifest is caught by manifest.test.ts.

import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CIRCUITS_DIR = path.join(__dirname, "..");
const TARGET_DIR = path.join(CIRCUITS_DIR, "target");
const MANIFEST_PATH = path.join(CIRCUITS_DIR, "manifest.json");

// I-1: CircuitId and public-input layouts (kakure master plan, Frozen interfaces).
const CIRCUITS = [
  { name: "deposit", circuit_id: 0, public_input_count: 13 },
  { name: "transfer", circuit_id: 1, public_input_count: 24 },
  { name: "withdraw", circuit_id: 2, public_input_count: 17 },
  { name: "transfer_multisig", circuit_id: 3, public_input_count: 24 },
  { name: "split_multisig", circuit_id: 4, public_input_count: 22 },
  { name: "join_multisig", circuit_id: 5, public_input_count: 14 },
  { name: "withdraw_multisig", circuit_id: 6, public_input_count: 17 },
];

async function sha256File(p) {
  const data = await readFile(p);
  return createHash("sha256").update(data).digest("hex");
}

export async function computeManifest() {
  const circuits = [];
  for (const c of CIRCUITS) {
    const vkPath = path.join(TARGET_DIR, `${c.name}.vk`);
    let vk_sha256;
    try {
      vk_sha256 = await sha256File(vkPath);
    } catch {
      throw new Error(
        `Missing ${vkPath} — run 'just build-circuits' before regenerating the manifest.`,
      );
    }
    circuits.push({
      name: c.name,
      circuit_id: c.circuit_id,
      public_input_count: c.public_input_count,
      vk_sha256,
      setup: "INSECURE-DEV",
    });
  }
  return {
    description:
      "Kakure v1 circuit manifest: per-circuit CircuitId (I-1), flat public-input count (I-1), sha256 of the built Sunspot verifying key, and the toxic-waste provenance of that key's trusted setup. Regenerated by circuits/scripts/gen_manifest.mjs; drift-tested by circuits/manifest.test.ts.",
    circuits,
  };
}

async function main() {
  const manifest = await computeManifest();
  const json = JSON.stringify(manifest, null, 2) + "\n";

  if (process.argv.includes("--check")) {
    let existing;
    try {
      existing = await readFile(MANIFEST_PATH, "utf8");
    } catch {
      console.error(`FAIL: ${MANIFEST_PATH} does not exist.`);
      process.exit(1);
    }
    if (existing !== json) {
      console.error(`FAIL: ${MANIFEST_PATH} does not match freshly computed manifest (drift detected).`);
      process.exit(1);
    }
    console.log(`OK: ${MANIFEST_PATH} matches freshly computed manifest.`);
  } else {
    await writeFile(MANIFEST_PATH, json);
    console.log(`Wrote ${MANIFEST_PATH} (${manifest.circuits.length} circuits).`);
  }
}

// Only run as a script (not when imported by manifest.test.ts).
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
