#!/usr/bin/env node
// Generates (or, with --check, verifies) circuits/kat/lean_imt_poseidon_v1.json.
//
// Independently computes the LeanIMT KAT using circomlibjs's Poseidon (circom parameters),
// which the vendored Noir `poseidon` crate's `poseidon::poseidon::bn254::hash_3` is
// cross-checked against in shared/src/lib.nr::kat_cross_check_hash_3. Two independent
// implementations (this script, and the Noir test `kat_lean_imt_poseidon_v1` in
// shared/src/lib.nr, which replays the siblings below through
// `lean_imt_inclusion_proof`) must agree byte-for-byte on every root and sibling.
//
// Tree shape: a LeanIMT with N leaves has, at level L, `ceil(N / 2^L)` nodes:
//   node[L][j] = H(node[L-1][2j], node[L-1][2j+1], L-1)   if 2j+1 < len(node[L-1])
//   node[L][j] = node[L-1][2j]                             otherwise (lone node passes
//                                                            through unchanged: "zero
//                                                            sibling" case)
// `lean_imt_inclusion_proof(leaf, leaf_index, siblings)` (shared/src/lib.nr) walks all
// MAX_DEPTH=32 levels: at level L it uses `path_bits[L]` (bit L of leaf_index) to route
// left/right when `siblings[L] != 0`, and otherwise asserts `path_bits[L] == 0` (the
// "non-canonical leaf index" guard) — i.e. once a level has no real sibling, every
// leaf_index bit at and above that level must be 0. This holds naturally for a lone node
// (its position at that level is even) and for every level above the tree's actual height
// (position 0, always even).
//
// Leaves 1..8 (Field value == 1-based ordinal) are inserted sequentially, one per KAT
// entry, at leaf_index 0..7. For each entry we record the resulting root (after N = index+1
// leaves) and that leaf's own 32-entry sibling path against that root, per the Kakure
// master plan, Workstream A task 3.

import { buildPoseidon } from "circomlibjs";
import { writeFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const DEPTH = 32;
const LEAVES = [1n, 2n, 3n, 4n, 5n, 6n, 7n, 8n];

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, "..", "kat", "lean_imt_poseidon_v1.json");

function toHex32(bi) {
  return "0x" + bi.toString(16).padStart(64, "0");
}

// Builds the full level pyramid (level 0 = leaves) for a LeanIMT over `leaves`.
function buildLevels(leaves, hash3) {
  const levels = [leaves.slice()];
  let cur = leaves;
  let level = 0;
  while (cur.length > 1) {
    const next = [];
    for (let j = 0; j * 2 < cur.length; j++) {
      const l = cur[2 * j];
      const r = cur[2 * j + 1];
      next.push(r === undefined ? l : hash3(l, r, BigInt(level)));
    }
    levels.push(next);
    cur = next;
    level++;
  }
  return levels; // levels[level][position]
}

// Extracts the depth-32 sibling path and root for `leafIndex` from a level pyramid.
function siblingsAndRoot(levels, leafIndex) {
  const siblings = new Array(DEPTH).fill(0n);
  let p = leafIndex;
  for (let level = 0; level < levels.length - 1; level++) {
    const nodesAtLevel = levels[level];
    const partnerPos = p % 2 === 0 ? p + 1 : p - 1;
    siblings[level] = partnerPos < nodesAtLevel.length ? nodesAtLevel[partnerPos] : 0n;
    p = Math.floor(p / 2);
  }
  // Above the tree's actual height, siblings are 0 and leafIndex's remaining bits must be 0
  // (guaranteed: leafIndex < number of leaves <= 8, far below 2^(levels.length - 1) here).
  const root = levels[levels.length - 1][0];
  return { siblings, root };
}

async function main() {
  const poseidon = await buildPoseidon();
  const F = poseidon.F;
  const hash3 = (a, b, c) => F.toObject(poseidon([a, b, c]));

  const entries = [];

  // Genesis case: empty depth-32 tree, nothing inserted yet.
  entries.push({
    case: "genesis",
    leaf_index: null,
    leaf: null,
    next_leaf_index: 0,
    root: toHex32(0n),
    siblings: new Array(DEPTH).fill(0n).map(toHex32),
  });

  for (let i = 0; i < LEAVES.length; i++) {
    const leafIndex = i; // 0-based
    const leaves = LEAVES.slice(0, i + 1); // tree state right after this insert
    const levels = buildLevels(leaves, hash3);
    const { siblings, root } = siblingsAndRoot(levels, leafIndex);

    entries.push({
      case: `leaf_${i + 1}`,
      leaf_index: leafIndex,
      leaf: toHex32(LEAVES[i]),
      next_leaf_index: i + 1,
      root: toHex32(root),
      siblings: siblings.map(toHex32),
    });
  }

  const kat = {
    description:
      "LeanIMT depth-32 KAT, Poseidon v1 (circom parameters), node = poseidon_v1([left, right, level]). Generated by circuits/scripts/gen_lean_imt_kat.mjs (circomlibjs) and cross-checked against a Noir computation (kat_lean_imt_poseidon_v1 in shared/src/lib.nr) using the vendored poseidon crate's hash_3. See kakure master plan, Workstream A task 3.",
    hash: "poseidon_v1_hash_3",
    depth: DEPTH,
    entries,
  };

  const json = JSON.stringify(kat, null, 2) + "\n";

  if (process.argv.includes("--check")) {
    let existing;
    try {
      existing = await readFile(OUT_PATH, "utf8");
    } catch {
      console.error(`FAIL: ${OUT_PATH} does not exist. Run without --check to generate it.`);
      process.exit(1);
    }
    if (existing !== json) {
      console.error(`FAIL: ${OUT_PATH} does not match freshly computed KAT (drift detected).`);
      process.exit(1);
    }
    console.log(`OK: ${OUT_PATH} matches freshly computed KAT (${entries.length} entries).`);
  } else {
    await writeFile(OUT_PATH, json);
    console.log(`Wrote ${OUT_PATH} (${entries.length} entries).`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
