// Cross-check against workstream A's shared KAT (`circuits/kat/lean_imt_poseidon_v1.json`, generated by
// circomlibjs and replayed in Noir). The indexer's tree uses `poseidon-lite` (see `poseidonV1.ts`) while
// `@kakure/sdk`'s LeanIMT uses `circomlibjs` directly -- both must reproduce this KAT bit-for-bit, since it
// is also what `kakure_pool`'s on-chain frontier insert (`sol_poseidon`) is checked against. If this ever
// fails, the KAT is authoritative -- fix `poseidonV1.ts`/`leanImt.ts` here (or `@kakure/sdk`'s equivalents),
// never the fixture.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { LeanIMT } from "./leanImt.js";
import { fieldFromHex, fieldToHex } from "./poseidonV1.js";

const KAT_PATH = fileURLToPath(
  new URL("../../../../circuits/kat/lean_imt_poseidon_v1.json", import.meta.url),
);

interface KatEntry {
  readonly case: string;
  readonly leaf_index: number | null;
  readonly leaf: string | null;
  readonly next_leaf_index: number;
  readonly root: string;
  readonly siblings: readonly string[];
}
interface Kat {
  readonly depth: number;
  readonly entries: readonly KatEntry[];
}

function loadKat(): Kat {
  try {
    return JSON.parse(readFileSync(KAT_PATH, "utf8")) as Kat;
  } catch (err) {
    const why = err instanceof Error ? err.message : String(err);
    throw new Error(
      `circuits/kat/lean_imt_poseidon_v1.json missing or unreadable at ${KAT_PATH} (${why}). ` +
        "Workstream A publishes this fixture; run `git merge main` if it is missing here.",
    );
  }
}

describe("LeanIMT vs workstream A's shared KAT (circuits/kat/lean_imt_poseidon_v1.json)", () => {
  const kat = loadKat();

  it("has the expected shape (depth 32, genesis case + leaves 1..8)", () => {
    expect(kat.depth).toBe(32);
    expect(kat.entries.length).toBe(9);
    expect(kat.entries[0]!.case).toBe("genesis");
  });

  it("reproduces every root and 32-sibling path bit-for-bit", () => {
    const tree = new LeanIMT(kat.depth);

    for (const entry of kat.entries) {
      if (entry.case === "genesis") {
        // Pre-insert state: nothing has been inserted yet, so there is no valid leaf index to fetch a
        // path for -- only the (zero) root is checked.
        expect(tree.nextLeafIndex).toBe(entry.next_leaf_index);
        expect(fieldToHex(tree.getRoot())).toBe(entry.root);
        continue;
      }

      tree.insert(fieldFromHex(entry.leaf!));

      expect(tree.nextLeafIndex).toBe(entry.next_leaf_index);
      expect(fieldToHex(tree.getRoot())).toBe(entry.root);

      const siblings = tree.getPath(entry.leaf_index!);
      expect(siblings.map(fieldToHex)).toEqual(entry.siblings);
    }
  });
});
