[package]
name = "transfer_multisig"
type = "bin"
authors = ["Kakure Labs"]
license = "Apache-2.0"

[dependencies]
shared = { path = "../../shared" }
ecdh = { path = "../../vendor/ecdh" }
poseidon = { path = "../../vendor/poseidon" }
