import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeManifest } from "./scripts/gen_manifest.mjs";
import { isG1Infinity, parseGnarkVk } from "./scripts/vk.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = path.join(__dirname, "manifest.json");
const TARGET_DIR = path.join(__dirname, "target");
const CIRCUIT_NAMES = [
  "deposit",
  "transfer",
  "withdraw",
  "transfer_multisig",
  "split_multisig",
  "join_multisig",
  "withdraw_multisig",
];

// Drift test: circuits/manifest.json must exactly match what gen_manifest.mjs computes right
// now from the built .vk files under circuits/target/. If a circuit is rebuilt (its .ccs/.pk/.vk
// regenerated by `just build-circuits`) and the committed manifest.json isn't regenerated to
// match (`just build-manifest`), this test fails.
describe("circuits/manifest.json", () => {
  it("matches the freshly computed manifest (no drift)", async () => {
    const committed = JSON.parse(await readFile(MANIFEST_PATH, "utf8"));
    const fresh = await computeManifest();
    expect(committed).toEqual(fresh);
  });

  it("covers all 7 v1 circuits with the frozen I-1 CircuitIds and public input counts", async () => {
    const committed = JSON.parse(await readFile(MANIFEST_PATH, "utf8"));
    const expected = [
      ["deposit", 0, 13],
      ["transfer", 1, 24],
      ["withdraw", 2, 17],
      ["transfer_multisig", 3, 24],
      ["split_multisig", 4, 22],
      ["join_multisig", 5, 14],
      ["withdraw_multisig", 6, 17],
    ];
    expect(committed.circuits).toHaveLength(expected.length);
    for (const [name, circuit_id, public_input_count] of expected) {
      const entry = committed.circuits.find((c: { name: string }) => c.name === name);
      expect(entry, `manifest missing circuit ${name}`).toBeDefined();
      expect(entry.circuit_id).toBe(circuit_id);
      expect(entry.public_input_count).toBe(public_input_count);
      expect(entry.setup).toBe("INSECURE-DEV");
      expect(entry.vk_sha256).toMatch(/^[0-9a-f]{64}$/);
    }
  });
});

// Generic Groth16 public-input-binding guard (slice-2 F-1). Under Groth16 the verifier checks
// e(A,B) = e(alpha,beta) * e(Σ pub_i * K[i], gamma) * e(C, delta); a public wire with zero
// occurrences in the R1CS gets K[i] = the point at infinity, so that term contributes nothing and
// the wire is NOT actually bound by the proof -- exactly what happened to withdraw's `_recipient`/
// `_intent_hash` before the fix. This walks every committed `circuits/target/<name>.vk` (gnark's
// raw `WriteRawTo` layout, see `scripts/vk.mjs`) and asserts none of its public-input K[i] points
// are the point at infinity (all-zero 64-byte G1). It is a static, circuit-agnostic replacement
// for having to hand-verify each circuit's outputs with `sunspot verify` + bit flips.
describe("every circuit's committed .vk binds every public input (slice-2 F-1)", () => {
  for (const name of CIRCUIT_NAMES) {
    it(`${name}.vk: no public-input K[i] is the point at infinity`, async () => {
      const buf = await readFile(path.join(TARGET_DIR, `${name}.vk`));
      const vk = parseGnarkVk(buf);
      const infinityIndices = vk.publicInputK
        .map((k, i) => (isG1Infinity(k) ? i : -1))
        .filter((i) => i >= 0);
      expect(
        infinityIndices,
        `${name}.vk has unbound (K[i] = infinity) public input(s) at indices ${infinityIndices.join(", ")}`,
      ).toEqual([]);
    });
  }

  // Regression proof, not just a unit test of the parser: the OLD withdraw.vk (built before the
  // F-1 fix, sha256 8685c208...73308, preserved as a fixture because circuits/target/ is
  // untracked) has exactly two unbound public inputs -- index 1 (`_recipient`) and index 2
  // (`_intent_hash`) -- which is the bug this guard exists to catch. The rebuilt withdraw.vk
  // (sha256 ca201e9a...690cd, current manifest.json) has none. This proves the guard actually
  // discriminates the vulnerable key from the fixed one, not just that it runs.
  it("fails on the pre-fix withdraw.vk (recipient/intent_hash unbound) and passes on the rebuilt one", async () => {
    const oldVk = parseGnarkVk(await readFile(path.join(__dirname, "kat/fixtures/withdraw.old-vulnerable.vk")));
    const oldInfinityIndices = oldVk.publicInputK
      .map((k, i) => (isG1Infinity(k) ? i : -1))
      .filter((i) => i >= 0);
    expect(oldInfinityIndices).toEqual([1, 2]);

    const newVk = parseGnarkVk(await readFile(path.join(TARGET_DIR, "withdraw.vk")));
    const newInfinityIndices = newVk.publicInputK
      .map((k, i) => (isG1Infinity(k) ? i : -1))
      .filter((i) => i >= 0);
    expect(newInfinityIndices).toEqual([]);
  });
});
