/**
 * A recipient's "Kakure pay address": their `canonicalIncomingAddress(index)` PUBLIC point, shared
 * once with whoever will pay them privately (like sharing a bank account number). Minting an
 * incoming note (`note/mint.ts`'s `mintIncomingNote`) needs this point, and it can only come from
 * the recipient's own view key -- a sender has no way to derive it unasked. This is a distinct
 * concept from the claim LINK (`claimToken.ts`), which is generated by the sender AFTER paying and
 * never carries key material either way.
 */
import type { SolanaAccount } from "@kakure/sdk";

export interface ReceiveAddress {
  index: bigint;
  pubX: bigint;
  pubY: bigint;
}

export async function myReceiveAddress(account: SolanaAccount, index = 0n): Promise<ReceiveAddress> {
  const addr = await account.canonicalIncomingAddress(index);
  return { index: addr.index, pubX: addr.pub[0], pubY: addr.pub[1] };
}

export function encodeReceiveAddress(addr: ReceiveAddress): string {
  const json = JSON.stringify({ index: addr.index.toString(), pubX: addr.pubX.toString(), pubY: addr.pubY.toString() });
  return btoa(unescape(encodeURIComponent(json))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function decodeReceiveAddress(encoded: string): ReceiveAddress {
  const b64 = encoded.replace(/-/g, "+").replace(/_/g, "/");
  const json = decodeURIComponent(escape(atob(b64)));
  const parsed = JSON.parse(json) as { index: string; pubX: string; pubY: string };
  return { index: BigInt(parsed.index), pubX: BigInt(parsed.pubX), pubY: BigInt(parsed.pubY) };
}
